swagger: "2.0"

info:
  title: user-service-v1
  version: "1.0"

securityDefinitions:
  Authorization:
    type: apiKey
    in: header
    name: Authorization

paths:
  /v1/login:
    post:
      operationId: login
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/LoginPayLoad"
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/LoginResponse"
        '500':
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /v1/profile:
    get:
      operationId: getProfile
      security:
        - Authorization: []
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/UserProfile"
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      operationId: putProfile
      security:
        - Authorization: []
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/PutProfilePayLoad"
      responses:
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        '400':
          description: BadRequest
          schema:
            $ref: "#/definitions/ErrorResponse"
        '200':
          description: Success
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/UserProfile"
  /v1/connect_twitter:
    put:
      operationId: connectTwitter
      security:
        - Authorization: []
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/ConnectTwitterPayLoad"
      responses:
        '401':
          description: Unauthorized
          schema:
            $ref: "#/definitions/ErrorResponse"
        '400':
          description: BadRequest
          schema:
            $ref: "#/definitions/ErrorResponse"
        '200':
          description: Success
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/UserProfile"
definitions:
  LoginResponse:
    type: object
    required:
      - jwt
    properties:
      jwt:
        type: string
  LoginPayLoad:
    type: object
    required:
      - address
      - signature
      - origin_message
    properties:
      address:
        type: string
      signature:
        type: string
      origin_message:
        type: string
  UserProfile:
    type: object
    required:
      - id
    properties:
      id:
        type: string
      name:
        type: string
      address:
        type: string
      twitter:
        type: string
      discord:
        type: string
  PutProfilePayLoad:
    type: object
    properties:
      name:
        type: string
      address:
        type: string
  ErrorResponse:
    type: object
    required:
      - error
    properties:
      error:
        type: string
  ConnectTwitterPayLoad:
    type: object
    properties:
      twitter:
        type: string
