[functions]
  directory = "functions/"

[context.dev]
  command = "env"

[context.dev.environment]
  APP_ENV = "DEV"

[context."feature/fushang318_login"]
  command = "env"

[context."feature/fushang318_login".environment]
  APP_ENV = "DEV"

[[plugins]]
package = "netlify-plugin-use-env-in-runtime"
  [plugins.inputs]
    prefix = "APP"
    def = ["APP_ENV"]
