[functions]
  directory = "functions/"

[context.dev]
  command = "env"
  [context.dev.environment]
    APP_ENV = "DEV"

[context."feature/fushang318_login"]
  command = "env"
  [context."feature/fushang318_login".environment]
    APP_ENV = "DEV"
