[functions]
  directory = "functions/"

[context.dev]
  command = "env"
  [environment]
    APP_ENV = "DEV"

[context."feature/fushang318_login"]
  command = "env"
  [environment]
    APP_ENV = "DEV"
